# 🐼 Pandas Lesson 1 — Quick Revision Notes

*Level 1 | DataFrames & Series*

---

## 1. What is Pandas?

Pandas is a Python library used to **organise, clean, manipulate and analyse data**.

```python
import pandas as pd
```

`pd` is the conventional alias for Pandas.

## 2. Series vs DataFrame

| Series | DataFrame |
|---|---|
| One-dimensional | Two-dimensional |
| One column of data | Rows and columns |
| `pd.Series([500, 900, 300])` | `pd.DataFrame({...})` |

**Memory trick:** Series = column; DataFrame = complete table.

## 3. Essential inspection commands

| Command | Purpose |
|---|---|
| `df.head()` | First 5 rows |
| `df.tail()` | Last 5 rows |
| `df.shape` | Rows and columns |
| `df.columns` | Column names |
| `df.dtypes` | Data types |
| `df.info()` | Dataset structure |
| `df.describe()` | Numeric statistics |
| `df.isnull().sum()` | Missing-value count |

> **Interview tip:** `df.shape` has no parentheses.

## 4. Selecting and filtering

```python
df["Salary"]                 # One column → Series
df[["Name", "Salary"]]       # Multiple columns → DataFrame
df[df["Salary"] > 25000]     # Filter rows
```

## 5. `.loc` vs `.iloc`

```python
df.loc[0, "Name"]  # Select by labels
df.iloc[0, 0]      # Select by integer positions
```

- `.loc` → labels
- `.iloc` → positions

## 6. Quick revision

1. **Inspect:** `head()`, `info()`, `shape`
2. **Select:** `df["column"]`
3. **Filter:** `df[df["column"] > value]`
4. **Locate:** `.loc[]` and `.iloc[]`

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Ana", "Riya", "Sam", "Dev"],
    "City": ["Mumbai", "Pune", "Mumbai", "Nashik"],
    "Age": [22, 25, 21, 28],
    "Salary": [25000, 40000, 22000, 50000]
})

print(df.head())

   Name    City  Age  Salary
0   Ana  Mumbai   22   25000
1  Riya    Pune   25   40000
2   Sam  Mumbai   21   22000
3   Dev  Nashik   28   50000

In [3]:
df["Salary"]

0    25000
1    40000
2    22000
3    50000
Name: Salary, dtype: int64

In [4]:
df[["Name", "Salary"]]

   Name  Salary
0   Ana   25000
1  Riya   40000
2   Sam   22000
3   Dev   50000

In [5]:
df[df["Salary"] > 25000]

   Name    City  Age  Salary
1  Riya    Pune   25   40000
3   Dev  Nashik   28   50000

In [6]:
df.loc[0, "Name"]

'Ana'

In [7]:
df.loc[1, "Name"]

'Riya'

In [8]:
df.iloc[0, 0]

'Ana'

In [9]:
df.iloc[0, 1]

'Mumbai'